AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI backend for PC Builder running on AWS Lambda
Resources:
  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: app.main.handler
      Runtime: python3.11
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          MY_AWS_REGION: eu-west-3
          S3_BUCKET: pc-builder-bucket-dvg-2025
          S3_CSV_KEY: graphics-cards.csv
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
